library(shiny)
library(rCharts)
shinyUI(fluidPage(
        h4("Records for Hits in MLB"), 
        h5("Players with all time hits over 2800"),
        sidebarPanel(
                sliderInput("H_cum", "Hits:",
                            min = 2800, max = 4500, value = c(3500, 4500))
        ),
        
    mainPanel(
                h5(
                        HTML('<body><h5>
                                <h4>Introduction</h4>
                                <P>This project generated visualized all-time hits 
                                record in Major League Baseball since 1871 to 2015. 
                                Data was limited to players whose hits record are 
                                above 2800.</P>
                                <P>The raw data was acquired from 
                                <a href="http://www.seanlahman.com">seanlahman.com</a>. 
                                If you are interested in analyzing on your own, 
                                you can download from my repository or directly 
                                from <a href="http://www.seanlahman.com/baseball-archive/statistics/">here</a>
                                . The copyright 1996-2016 belongs to 
                                Sean Lahman.</P>
                                <P>The visualized results can be viewed from 
                                here: <a href="https://eufmike.shinyapps.io/Records_for_Hits_in_MLB/">https://eufmike.shinyapps.io/Records_for_Hits_in_MLB/</a>
                                .
                                </P>
                                <br>
                                <h4>Brief Guidance</h4>
                                <P>
                                The visualized plot was generated by rCharts::nPlot, which utilized NVD3 for plotting and interaction. Users can explore the data by changing the total hits and observe the growing hits number for each player. Record of cumulative hits was plotted by year, age and the time they played for teams in MLB. The fourth chart demonstrated their batting average across their career.
                                </P>
                                <P>
                                It is important to mention that NVD3 is not ideal for handle this type of data with data points over a thousand, so please be patient when you try to include all players into the charts.
                                </P>
                                <P>© Chien-cheng Shih 2016 All Rights Reserved.</P>
                                <br>
                                </h5></body>
                             ')
                ),

                h5('Information can be checked by hovering over each point', 
                   align ="center"),
                
                h4('Hits by Year', align = "center"),
                showOutput("plot1", "nvd3"),
                h4('Hits by Age', align = "center"),
                showOutput("plot2", "nvd3"),
                h4('Hits by seniority in MLB', align = "center"),
                showOutput("plot3", "nvd3"),
                h4('Batting average by age', align = "center"),
                showOutput("plot4", "nvd3")
                )
))
